version: '3.9'

services:
  api:
    build:
      context: ./server/
      target: development
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - db-data/:/root/db/
    ports:
      - "3307:3306"
    expose:
      - "3306"

volumes:
  db-data:
