apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  namespace: deel-infra-namespace
  name: registry-secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJkVzVqYTJ4bFp6cG5hSEJmTUdWemVIbEJhbmxOVVhkMWMyaFlRVlIwT0dzemNWb3pVRkpsVEdKd05FZFhWRTl6In19fQo=
